// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package a

import (
	"context"
	"github.com/simon/mengine/cmd"
)

// Injectors from a.go:

func InitializeBaz(ctx context.Context) (cmd.Baz, error) {
	foo := cmd.ProvideFoo()
	bar := cmd.ProvideBar(foo)
	baz, err := cmd.ProvideBaz(ctx, bar)
	if err != nil {
		return cmd.Baz{}, err
	}
	return baz, nil
}
