// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package engine

import (
	"context"
	"github.com/simon28082/mengine/infrastructure/logger/wrap"
	"github.com/simon28082/mengine/infrastructure/logger/zap"
)

// Injectors from wire.go:

func EngineProvide(ctx context.Context) Engine {
	engineEngine := NewEngine(ctx)
	return engineEngine
}

func LoggerProvide() *wrap.LoggerWrap {
	zapZap := zap.NewZapDevelopment()
	loggerWrap := wrap.NewLogger(zapZap)
	return loggerWrap
}
