// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package engine

import (
	"context"
	"github.com/simon28082/mengine/infrastructure/logger"
	"github.com/simon28082/mengine/infrastructure/logger/wrap"
	"github.com/simon28082/mengine/infrastructure/logger/zap"
)

// Injectors from wire.go:

func ProvideEngine(ctx context.Context) Engine {
	engineEngine := NewEngine(ctx)
	return engineEngine
}

// wire.go:

func ProvideZapDevLogger() logger.Wrap {
	return wrap.NewLogger(zap.NewZapDevelopment())
}

func ProvideZapProdLogger() logger.Wrap {
	return wrap.NewLogger(zap.NewZapProduction())
}
