// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/engine/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/simon/mengine/infrastructure/engine"
	"github.com/simon/mengine/infrastructure/container"
	"github.com/simon/mengine/infrastructure/provider"
	"github.com/simon/mengine/plugins/server/http"
)

// Injectors from main.go:

func InitProvider(ctx context.Context) provider.Provider {
	container := _wireContainerValue
	providerProvider := engine.NewProvider(ctx, container)
	return providerProvider
}

var (
	_wireContainerValue = container.NewContainer()
)

func InitHttpProvider(ctx context.Context) provider.Provider {
	containerContainer := _wireContainerValue
	providerProvider := http.NewProvider(ctx, containerContainer)
	return providerProvider
}

// main.go:

func main() {

	ctx := context.Background()
	rootProvider := InitProvider(ctx)
	httpProvider := InitHttpProvider(ctx)

	err := engine.Run(rootProvider, httpProvider)

	if err != nil {
		panic(err)
	}
}
